### PR TITLE
Added HACTOBERFEST.md

### PR DESCRIPTION
**Pull request by ASR8127**
it's required to add you to your repo 

Because you added a label of HACTOBERFEST

### CODE REVIEW

**Comment by giyasht** [comment]
It's a repo where you can add algorithms not spam with readme file containg link to register for hacktoberfest. So if you want to contribute make a valid pull request.

**Comment by ASR8127** [comment]
okay i do  valid pull request.

please remove spam

**Comment by giyasht** [comment]
Make a valid pull request, I will remove the tag.

**Comment by giyasht** [comment]
Since you made a valid pull request, I am removing the spam tag.

**Pull request closed without merging**
